project:
  type: book
  output-dir: _book

documentclass: book

github-repo: baeolophus/cast_iron_garden

book:
  title: "Cast Iron Garden: Plants for Scared People in Central Oklahoma"
  author: "C.M. Curry and P.M. Cimprich"
  search: true
  downloads: [pdf]
  page-footer: "Copyright 2024, Curry and Cimprich"
  description: "Plants for nervous gardeners."
  date: last-modified
  page-navigation: true
  reference-location: margin
  citation-location: margin
  chapters:
    - index.qmd
    - 01-the_really_really_short_version.qmd
    - part: gardening.qmd
      chapters:
        - 02-from_the_ground_up.qmd
        - 03-reduce_lawn.qmd
        - 04-trees.qmd
    - part: species_accounts.qmd
      chapters:
        - 05-species_accounts_example.qmd
    - 10-references.qmd
  appendices:
    - garden_maintenance_by_month.qmd
    - buying_plants.qmd

comments:
  hypothesis: true


bibliography:
  - references.bib
  - packages.bib

format:
  html:
    toc: false
    code-background: true
    code-copy: true
    css: style.css
    fontsize: 12pt
  pdf:
    documentclass: book
    include-in-header:
      text: |
        \usepackage{makeidx}
        \makeindex
    include-after-body:
      text: |
        \printindex
    keep-tex: false
    cite-method: natbib
